 export const deviceData = [
  {
    id: 'DVC001',
    type: 'Monitor',
    facility: 'AIIMS Delhi',
    status: 'Online',
    battery: 85,
    lastService: '2024-12-10',
    amcStatus: 'Active',
  },
  { 
    id: 'DVC002',
    type: 'Infusion Pump',
    facility: 'Apollo Mumbai',
    status: 'Maintenance',
    battery: 40,
    lastService: '2024-10-01',
    amcStatus: 'Expired',
  },
  {
    id: 'DVC003',
    type: 'Ventilator',
    facility: 'Fortis Bangalore',
    status: 'Offline',
    battery: 0,
    lastService: '2025-01-15',
    amcStatus: 'Inactive',
  },
  {
    id: 'DVC004',
    type: 'ECG Machine',
    facility: 'Medanta Gurgaon',
    status: 'Online',
    battery: 65,
    lastService: '2025-02-20',
    amcStatus: 'Active',
  },
  {
    id: 'DVC005',
    type: 'Defibrillator',
    facility: 'Max Saket',
    status: 'Online',
    battery: 78,
    lastService: '2025-03-01',
    amcStatus: 'Active',
  },
  {
    id: 'DVC006',
    type: 'X-Ray Machine',
    facility: 'AIIMS Bhopal',
    status: 'Maintenance',
    battery: 50,
    lastService: '2024-11-25',
    amcStatus: 'Expired',
  },
  {
    id: 'DVC007',
    type: 'Syringe Pump',
    facility: 'Narayana Health Kolkata',
    status: 'Online',
    battery: 95,
    lastService: '2025-06-01',
    amcStatus: 'Active',
  },
  {
    id: 'DVC008',
    type: 'Patient Monitor',
    facility: 'KIMS Hyderabad',
    status: 'Offline',
    battery: 10,
    lastService: '2025-04-15',
    amcStatus: 'Inactive',
  },
  {
    id: 'DVC009',
    type: 'Ultrasound Machine',
    facility: 'CMC Vellore',
    status: 'Online',
    battery: 88,
    lastService: '2025-01-10',
    amcStatus: 'Active',
  },
  {
    id: 'DVC010',
    type: 'Dialysis Machine',
    facility: 'AIIMS Rishikesh',
    status: 'Maintenance',
    battery: 55,
    lastService: '2024-09-05',
    amcStatus: 'Expired',
  },
  {
    id: 'DVC011',
    type: 'Infusion Pump',
    facility: 'Ruby Hall Pune',
    status: 'Online',
    battery: 70,
    lastService: '2025-05-12',
    amcStatus: 'Active',
  },
  {
    id: 'DVC012',
    type: 'Ventilator',
    facility: 'Sanjivani Raipur',
    status: 'Offline',
    battery: 0,
    lastService: '2025-02-28',
    amcStatus: 'Inactive',
  },
  {
    id: 'DVC013',
    type: 'ECG Machine',
    facility: 'Apollo Chennai',
    status: 'Online',
    battery: 90,
    lastService: '2025-03-18',
    amcStatus: 'Active',
  },
  {
    id: 'DVC014',
    type: 'Defibrillator',
    facility: 'Fortis Jaipur',
    status: 'Online',
    battery: 82,
    lastService: '2024-12-30',
    amcStatus: 'Active',
  },
  {
    id: 'DVC015',
    type: 'Patient Monitor',
    facility: 'AIIMS Patna',
    status: 'Maintenance',
    battery: 30,
    lastService: '2024-10-10',
    amcStatus: 'Expired',
  },
];
