export const deviceInputs = [
  {
    label: "Device ID",
    name: "deviceId",
    type: "text",
    id: "deviceId",
    section: "device",
    placeholder: "Enter device ID",
  },
  {
    label: "Device Name",
    name: "deviceName",
    type: "text",
    id: "deviceName",
    section: "device",
    placeholder: "Enter device Name",
  },
  {
    label: "Installation Place",
    name: "installationPlace",
    type: "text",
    id: "installationPlace",
    section: "device",
    placeholder: "Enter Installation Place",
  },
  {
    label: "Battery Percentage",
    name: "battery",
    type: "text",
    id: "battery",
    section: "device",
    placeholder: "Enter battery percentage",
  },
  {
    label: "Status",
    name: "status",
    type: "select",
    id: "status",
    section: "device",
    placeholder: "Select status",
    options: ["Online", "Offline", "Maintenance"],
  },

  {
    label: "AMC Status",
    name: "amcStatus",
    type: "select",
    id: "amcStatus",
    section: "device",
    placeholder: "Select AMC status",
    options: ["Active", "Offline"],
  },
  {
    label: "Device Image",
    name: "image",
    type: "file",
    id: "image",
    section: "device",
  },
  //*service
  {
    label: "Date",
    id: "date",
    type: "date",
    section: "ServiceVisitLog",
  },
  {
    label: "Responsible Engineer",
    id: "engineer",
    type: "text",
    section: "ServiceVisitLog",
  },
  {
    label: "Purpose",
    id: "purpose",
    type: "select",
    options: ["Preventive", "Breakdown"],
    section: "ServiceVisitLog",
  },
  {
    label: "Visit Notes",
    id: "visitNotes",
    type: "textarea",
    required: false,
    section: "ServiceVisitLog",
  },
  {
    label: "Attachment",
    id: "attachment",
    type: "file",
    acceptedTypes: ["image/*", "application/pdf"],
    required: false,
    section: "ServiceVisitLog",
  },
];
